/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"
#include "gpio.h"

static void delay(void)
{
    for(volatile uint32_t i = 0; i < 500000; i++);
}

int main(void)
{
    const uint8_t LedPins[3] = { GPIO_PIN_NO_12, GPIO_PIN_NO_13, GPIO_PIN_NO_14 };

    GPIO_PeriClockControl(GPIOD, ENABLE);

    for(uint8_t i = 0; i < 3; i++)
    {
        GPIO_Handle_t GpioLed = {0};

        GpioLed.pGPIOx                   = GPIOD;
        GpioLed.PinConfig.PinNumber      = LedPins[i];
        GpioLed.PinConfig.PinMode        = GPIO_MODE_OUTPUT;
        GpioLed.PinConfig.PinSpeed       = GPIO_SPEED_LOW;
        GpioLed.PinConfig.PinOPType      = GPIO_OUTPUT_PUSH_PULL;
        GpioLed.PinConfig.PinPuPdControl = GPIO_NO_PUPD;
        GpioLed.PinConfig.PinAltFunMode  = GPIO_AF0;

        GPIO_Init(&GpioLed);
    }

    for(;;)
    {
        for(uint8_t i = 0; i < 3; i++)
        {
            GPIO_TogglePin(GPIOD, LedPins[i]);
        }
        delay();
    }
}
