/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"
#include "gpio.h"
#include "rcc.h"
#include "spi.h"

SPI_Handle_t spi_handle;

#define SLAVE_CS_PORT   GPIOA
#define SLAVE_CS_PIN    GPIO_PIN_NO_4

void RCC_Config(void);
void GPIO_Config(void);
void SPI_Config(void);
void SlaveCS_Select(void);
void SlaveCS_Deselect(void);

int main(void)
{
    uint8_t txBuffer[2] = { 0x01, 0xAA };  //ornek: gonderilecek komut/veri
    uint8_t rxBuffer[2];

    RCC_Config();
    GPIO_Config();
    SPI_Config();

    //Slave ile tek transfer: ayni anda gonder ve al
    SlaveCS_Select();
    SPI_TransmitReceive(spi_handle.pSPIx, txBuffer, rxBuffer, 2);
    while(SPI_GetFlagStatus(spi_handle.pSPIx, SPI_SR_BUSY) == STATUS_OK);
    SlaveCS_Deselect();

    //rxBuffer artik slave'den gelen veriyi tutuyor

    while(1)
    {
    }
}

void RCC_Config(void)
{
    RCC_Config_t ClockConfig = {
        .OscSource     = RCC_OSC_HSE,
        .OscFreqHz     = 8000000UL,
        .UsePLL        = 1,
        .PLL           = { .PLL_M = 8, .PLL_N = 336, .PLL_P = 2, .PLL_Q = 7 },
        .AHBPrescaler  = RCC_AHB_DIV_1,
        .APB1Prescaler = RCC_APB_DIV_4,
        .APB2Prescaler = RCC_APB_DIV_2,
        .FlashLatency  = 5
    };

    if(RCC_Init(&ClockConfig) != RCC_OK)
    {
        while(1);  //saat agaci kurulamadi
    }
}

void GPIO_Config(void)
{
    GPIO_Handle_t gpio_handle;

    GPIO_PeriClockControl(GPIOA, ENABLE);

    //SCK, MISO, MOSI: SPI1 alternate function (AF5)
    gpio_handle.pGPIOx = GPIOA;
    gpio_handle.PinConfig.PinMode = GPIO_MODE_ALTERNATE_FUNCTION;
    gpio_handle.PinConfig.PinOPType = GPIO_OUTPUT_PUSH_PULL;
    gpio_handle.PinConfig.PinPuPdControl = GPIO_NO_PUPD;
    gpio_handle.PinConfig.PinSpeed = GPIO_SPEED_HIGH;
    gpio_handle.PinConfig.PinAltFunMode = GPIO_AF5;

    gpio_handle.PinConfig.PinNumber = GPIO_PIN_NO_5;  //SCK
    GPIO_Init(&gpio_handle);

    gpio_handle.PinConfig.PinNumber = GPIO_PIN_NO_6;  //MISO
    GPIO_Init(&gpio_handle);

    gpio_handle.PinConfig.PinNumber = GPIO_PIN_NO_7;  //MOSI
    GPIO_Init(&gpio_handle);

    //CS: duz GPIO cikisi (SSM_EN kullaniliyor, donanimsal NSS'e gerek yok)
    gpio_handle.PinConfig.PinNumber = SLAVE_CS_PIN;
    gpio_handle.PinConfig.PinMode = GPIO_MODE_OUTPUT;
    gpio_handle.PinConfig.PinAltFunMode = 0;
    GPIO_Init(&gpio_handle);

    SlaveCS_Deselect();  //baslangicta pasif (HIGH)
}

void SPI_Config(void)
{
    spi_handle.pSPIx = SPI1;

    spi_handle.spi_config.DeviceMode = DEVICE_MASTER;
    spi_handle.spi_config.BusConfig  = FULL_DUPLEX;
    spi_handle.spi_config.CPOL       = CPOL_0;
    spi_handle.spi_config.CPHA       = CPHA_0;
    spi_handle.spi_config.DFF        = DATA_8_BIT;
    spi_handle.spi_config.SclkSpeed  = SCLK_DIV8;
    spi_handle.spi_config.SSM        = SSM_EN;

    SPI_Init(&spi_handle);
    SPI_PeripheralControl(spi_handle.pSPIx, ENABLE);
}

void SlaveCS_Select(void)
{
    GPIO_WriteToPin(SLAVE_CS_PORT, SLAVE_CS_PIN, GPIO_PIN_RESET);
}

void SlaveCS_Deselect(void)
{
    GPIO_WriteToPin(SLAVE_CS_PORT, SLAVE_CS_PIN, GPIO_PIN_SET);
}
